string.execute) currently make use of java.lang.Process under the covers, the deficiencies of that class must currently be taken into consideration. With the method consumeProcessOutput() this issue looks is fixed.
[buildoop-github-#41]

diff --git a/recipes/oozie/oozie-4.0.0_openbus-0.0.1-r1/rpm/sources/rpm-build-stage b/recipes/oozie/oozie-4.0.0_openbus-0.0.1-r1/rpm/sources/rpm-build-stage
--- a/recipes/oozie/oozie-4.0.0_openbus-0.0.1-r1/rpm/sources/rpm-build-stage
+++ b/recipes/oozie/oozie-4.0.0_openbus-0.0.1-r1/rpm/sources/rpm-build-stage
@@ -36,28 +36,10 @@ set -x
     RELEASE_DIR=$PWD
 
 #
-# Resolve build version
-#
-    RELEASE_ENV_FILENAME=release.env
-    RELEASE_ENV_FILE=${RELEASE_DIR}/cloudera/${RELEASE_ENV_FILENAME}
-    if [ -f "${RELEASE_ENV_FILE}" ]; then
-        echo "Setting release environment using ${RELEASE_ENV_FILE}"
-        . ${RELEASE_ENV_FILE}
-    fi
-
-# IMPORTANT: THE FULL_VERSION, if set, will be used only for the final TARBALL,
-#            Everything inside of the TARBALL uses the version specified in the POM
-    if [ -z "${FULL_VERSION}" ]; then
-        FULL_VERSION=${OOZIE_VERSION}
-        echo "Warning: FULL_VERSION not specified. Default version [${FULL_VERSION}] will be used."
-    fi
-    VERSION_SUFFIX="-${FULL_VERSION}"
-
-#
 # Build Oozie
 #
 
-    echo "Starting system build"
+echo "Starting system build"
 
 # Test if there is a + sign in the dir path
 # We need to do this because in Linux Sun JVM inteprets '+' as ' ' in URLs
@@ -78,33 +60,32 @@ set -x
 
     EXTRA_GOALS=""
 
-# Check if maven deploy should be done or not
-    if [ "${DO_MAVEN_DEPLOY}" = "deploy" ]; then
-        EXTRA_GOALS="${EXTRA_GOALS} source:jar deploy"
-    fi
 
-# We need to build twice: once to generate the MR1 sharelib, again to generate the YARN sharelib
-    MKDISTRO_OPTIONS="-DskipTests -Dnot.cdh.release.build=false ${EXTRA_GOALS} -Dmaven.repo.local=${HOME}/.m2/repository $@"
+MKDISTRO_OPTIONS="-DskipTests ${EXTRA_GOALS} -Dmaven.repo.local=${HOME}/.m2/repository $@"
 
-    JAVA_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" ${WORKDIR}/bin/mkdistro.sh $MKDISTRO_OPTIONS -Pmr1
-    MKDISTRO_RESULT_MR1=$?
-    if [ "${MKDISTRO_RESULT_MR1}" != "0" ]; then
-        echo "ERROR: mkdistro.sh failed with error ${MKDISTRO_RESULT_MR1}"
-        echo "Build files from failed build: ${WORKDIR}"
-        exit ${MKDISTRO_RESULT_MR1}
-    fi
-    SHARELIB=${WORKDIR}/distro/target/oozie-*-distro/oozie-*/oozie-sharelib-*-sharelib.tar.gz
-    cp $SHARELIB ${RELEASE_DIR}/oozie-sharelib-${FULL_VERSION}.tar.gz
+#
+#    JAVA_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" ${WORKDIR}/bin/mkdistro.sh $MKDISTRO_OPTIONS -Pmr1
+#    MKDISTRO_RESULT_MR1=$?
+#    if [ "${MKDISTRO_RESULT_MR1}" != "0" ]; then
+#        echo "ERROR: mkdistro.sh failed with error ${MKDISTRO_RESULT_MR1}"
+#        echo "Build files from failed build: ${WORKDIR}"
+#        exit ${MKDISTRO_RESULT_MR1}
+#    fi
+#    SHARELIB=${WORKDIR}/distro/target/oozie-*-distro/oozie-*/oozie-sharelib-*.tar.gz
+#    cp $SHARELIB ${RELEASE_DIR}/oozie-sharelib-${FULL_VERSION}.tar.gz
 
-    JAVA_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" ${WORKDIR}/bin/mkdistro.sh $MKDISTRO_OPTIONS
-    MKDISTRO_RESULT=$?
-    if [ "${MKDISTRO_RESULT}" != "0" ]; then
+JAVA_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" \
+MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" \
+${WORKDIR}/bin/mkdistro.sh $MKDISTRO_OPTIONS
+
+MKDISTRO_RESULT=$?
+if [ "${MKDISTRO_RESULT}" != "0" ]; then
         echo "ERROR: mkdistro.sh failed with error ${MKDISTRO_RESULT}"
         echo "Build files from failed build: ${WORKDIR}"
         exit ${MKDISTRO_RESULT}
-    fi
-    SHARELIB=${WORKDIR}/distro/target/oozie-*-distro/oozie-*/oozie-sharelib-*-sharelib.tar.gz
-    cp $SHARELIB ${RELEASE_DIR}/oozie-sharelib-${FULL_VERSION}-yarn.tar.gz
+fi
+SHARELIB=${WORKDIR}/distro/target/oozie-*-distro/oozie-*/oozie-sharelib-*.tar.gz
+cp $SHARELIB ${RELEASE_DIR}/oozie-sharelib-${FULL_VERSION}-yarn.tar.gz
 
 #
 # Expand Oozie TAR and create CDH Ooozie TAR
@@ -162,7 +143,7 @@ set -x
             mv ${URLSAFE_NAME} ${ORIGINAL_NAME}
         fi
 
-        rm ${ORIGINAL_NAME}/oozie-sharelib-*-sharelib.tar.gz
+        rm ${ORIGINAL_NAME}/oozie-sharelib-*.tar.gz
         mv ${ORIGINAL_NAME}/src/oozie-sharelib-*.tar.gz ${ORIGINAL_NAME}/
 
         tar cfz oozie${VERSION_SUFFIX}.tar.gz ${ORIGINAL_NAME}
